language: php
php:
- '5.6'
before_script:
- composer install
cache:
  directories:
  - vendor
script: phpunit test/*Test.php 
after_success:
# notify Docker Hub to make a new build
- >
  [ "$TRAVIS_BRANCH" == "master" ]
  && curl -X POST -H "Content-Type: application/json"
  --data '{"docker_tag_name": "latest"}' $DOCKER_URL

