deployment:
    dockerhub:
        branch: master
        commands:
          - $DOCKER_HUB_TRIGGER
          
language: php
php:
  - '5.6'
before_script:
  - composer install
cache:
  directories: 
    - vendor
script: phpunit test/*Test.php